image: tiangolo/docker-with-compose

before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
    - build
    - deploy

build-prod:
    stage: build
    script:
        - docker-compose -f docker-compose.prod.yml build
        - docker-compose -f docker-compose.prod.yml push
    only:
        - master
    tags:
        - build
    
deploy-prod:
    stage: deploy
    script:
        - docker stack deploy -c docker-compose.prod.yml --with-registry-auth production
    only:
        - master
    tags:
        - swarm
      
