version: "3.7"

services:
  backend_api:
    image: '${CI_REGISTRY_IMAGE}/api:latest'
    container_name: backend-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DBPORT=${DBPORT}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
      - DEFAULT_USER_PASSWORD=${DEFAULT_USER_PASSWORD}
      - AUTH_JWT_SECRET=${AUTH_JWT_SECRET}
      - PUBLIC_API_KEY_TOKEN=${PUBLIC_API_KEY_TOKEN}
      - USER_API_KEY_TOKEN=${USER_API_KEY_TOKEN}
      - ADMIN_API_KEY_TOKEN=${ADMIN_API_KEY_TOKEN}
      - SELLER_API_KEY_TOKEN=${SELLER_API_KEY_TOKEN}
      - PAYPAL_ACCESS_TOKEN=${PAYPAL_ACCESS_TOKEN}
    deploy:
      labels:
        - traefik.frontend.rule=Host:api.kod3rsstore.com
        - traefik.enable=true
        - traefik.port=3000
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    networks:
      - traefik-public
  developers:
    image: '${CI_REGISTRY_IMAGE}/developers:latest'
    container_name: developers 
    build:
      context: ./developerDocumentation
      dockerfile: Dockerfile
    deploy:
      labels:
        - traefik.frontend.rule=Host:developers.kod3rsstore.com
        - traefik.enable=true
        - traefik.port=3000
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    networks:
      - traefik-public
  internal:
    image: '${CI_REGISTRY_IMAGE}/internal:latest'
    container_name: internal
    build:
      context: ./internaldocs
      dockerfile: Dockerfile
    deploy:
      labels:
        - traefik.frontend.rule=Host:internal.kod3rsstore.com
        - traefik.enable=true
        - traefik.port=3000
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    networks:
      - traefik-public    
networks:
  traefik-public:
    external: true
        
            
  
